// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_ggdna_version.test.ts.

/** The version of the `@ggdna/dna-ggdna` package. */
export const dnaGgdnaVersion = '0.2.0';
